spring.application.name=shop-app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopapp
spring.datasource.username=shopapp
spring.datasource.password=shopapp
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:29092

# Moments API
spring.modulith.moments.enable-time-machine=false
spring.modulith.moments.zone-id=Europe/Berlin

# Observability
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]
